Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\products\views.py", line 88, in products_list
    return render(request, 'products/products.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'products/main.css'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\products\views.py", line 88, in products_list
    return render(request, 'products/products.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 516, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'products/main.css'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 26, in __getitem__
    return self._storages[alias]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\products\views.py", line 88, in products_list
    return render(request, 'products/products.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 540, in _setup
    self._wrapped = storages[STATICFILES_STORAGE_ALIAS]
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 34, in __getitem__
    storage = self.create_storage(params)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 46, in create_storage
    return storage_cls(**options)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\whitenoise\storage.py", line 64, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 459, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 111, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\storage.py", line 29, in __init__
    check_settings(base_url)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\staticfiles\utils.py", line 49, in check_settings
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the required STATIC_URL setting.
"GET / HTTP/1.1" 500 145
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\views.py", line 56, in LoginPage
    return render(request, 'users/login.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
"GET /login/ HTTP/1.1" 500 84555
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\views.py", line 56, in LoginPage
    return render(request, 'users/login.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
"GET /login/ HTTP/1.1" 500 84692
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\views.py", line 56, in LoginPage
    return render(request, 'users/login.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
"GET /login/ HTTP/1.1" 500 84692
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\views.py", line 56, in LoginPage
    return render(request, 'users/login.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login.html
"GET /login/ HTTP/1.1" 500 84692
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 26, in __getitem__
    return self._storages[alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 29, in __getitem__
    params = self.backends[alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\products\views.py", line 88, in products_list
    return render(request, 'products/products.html', context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\fields\files.py", line 70, in url
    return self.storage.url(self.name)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\__init__.py", line 23, in _setup
    self._wrapped = storages[DEFAULT_STORAGE_ALIAS]
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\files\storage\handler.py", line 31, in __getitem__
    raise InvalidStorageError(
django.core.files.storage.handler.InvalidStorageError: Could not find config for 'default' in settings.STORAGES.
"GET / HTTP/1.1" 500 219979
Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\views.py", line 21, in register
    form.save()
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\forms.py", line 256, in save
    user = self.set_password_and_save(user, commit=commit)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\forms.py", line 165, in set_password_and_save
    user.save()
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 1012, in save_base
    post_save.send(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\HP\Documents\django-project\shoply\users\signals.py", line 18, in add_to_group
    group = Group.objects.get(name='seller')
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
"POST /register/ HTTP/1.1" 500 111623
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\admin\sites.py", line 444, in login
    return LoginView.as_view(**defaults)(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\views.py", line 108, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\models.py", line 24, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 1012, in save_base
    post_save.send(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\HP\Documents\django-project\shoply\users\signals.py", line 30, in save_profile
    instance.profile.save()
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\fields\related_descriptors.py", line 531, in __get__
    raise self.RelatedObjectDoesNotExist(
users.models.CustomUser.profile.RelatedObjectDoesNotExist: CustomUser has no profile.
"POST /admin/login/?next=/admin/ HTTP/1.1" 500 188211
Internal Server Error: /dashboard/flemzy/
Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply\users\views.py", line 36, in dashboard_view
    dashboard = Dashboard.objects.get(dashboard_user__username=username)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
users.models.Dashboard.DoesNotExist: Dashboard matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_dashboard_dashboard_user_id_key"
DETAIL:  Key (dashboard_user_id)=(1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\decorators.py", line 29, in wrapper_func
    return view_func(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\decorators.py", line 18, in wrapper_func
    return view_func(request, *args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply\users\views.py", line 38, in dashboard_view
    dashboard = Dashboard.objects.create(dashboard_user=request.user)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HP\Documents\django-project\shoply-env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "users_dashboard_dashboard_user_id_key"
DETAIL:  Key (dashboard_user_id)=(1) already exists.

"GET /dashboard/flemzy/ HTTP/1.1" 500 170196
